2024-03-26 21:58:45,039 INFO:app:Files stored with ids: [ObjectId('6602f7bdc60c3f8327957964')] for username: Harshvardhan
2024-03-26 21:58:45,041 ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/Career-Guidance/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/Career-Guidance/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/Career-Guidance/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Career-Guidance/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/Career-Guidance/app.py", line 536, in upload_file
    report = resume_report(os.path.join(app.config['UPLOAD_FOLDER'], f"{username}_document.jpg"))
  File "/home/ubuntu/Career-Guidance/app.py", line 406, in resume_report
    resume = PIL.Image.open(file_path)
  File "/home/ubuntu/Career-Guidance/venv/lib/python3.10/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'uploads/Harshvardhan_document.jpg'
